# -*- coding: utf-8 -*-
"""Hotels_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOLJ912_p8wmAnraIz-NKBQkt2JK2JBx

<h2 align="center">Hotels Data Analysis Project<h2>
"""

import pandas as pd

"""***
### ==> 1. Data Import and Data Exploration
***

### Datasets
We have 5 csv file

   - dim_date.csv  
   - dim_hotels.csv
   - dim_rooms.csv
   - fact_aggregated_bookings
   - fact_bookings.csv

**Read bookings data in a datagrame**
"""

df_bookings = pd.read_csv('/content/fact_bookings.csv')

"""**Explore bookings data**"""

df_bookings.head()

df_bookings.shape

df_bookings.room_category.unique()

df_bookings.booking_platform.unique()

df_bookings.booking_platform.value_counts()

df_bookings.booking_platform.value_counts().plot(kind="bar")

df_bookings.describe()

"""**Read rest of the files**"""

df_date = pd.read_csv('/content/dim_date.csv')
df_hotels = pd.read_csv('/content/dim_hotels.csv')
df_rooms = pd.read_csv('/content/dim_rooms.csv')
df_agg_bookings = pd.read_csv('/content/fact_aggregated_bookings.csv')

df_hotels.shape

df_hotels.head(3)

df_hotels.category.value_counts()

df_hotels.city.value_counts().plot(kind="bar")

"""***
**Explore aggregate bookings**
***
"""

df_agg_bookings.head(3)

df_agg_bookings.property_id.unique()

df_agg_bookings.groupby("property_id")["successful_bookings"].sum()

df_agg_bookings[df_agg_bookings.successful_bookings>df_agg_bookings.capacity]

df_agg_bookings.capacity.max()

df_agg_bookings[df_agg_bookings.capacity==df_agg_bookings.capacity.max()]

"""***
### ==> 2. Data Cleaning
***
"""

df_bookings.describe()

"""**(1) Clean invalid guests**"""

df_bookings[df_bookings.no_guests<=0]

"""As you can see above, number of guests having less than zero value represents data error. We can ignore these records."""

df_bookings = df_bookings[df_bookings.no_guests>0]

df_bookings.shape

"""**(2) Outlier removal in revenue generated**"""

df_bookings.revenue_generated.min(), df_bookings.revenue_generated.max()

df_bookings.revenue_generated.mean(), df_bookings.revenue_generated.median()

avg, std = df_bookings.revenue_generated.mean(), df_bookings.revenue_generated.std()

higher_limit = avg + 3*std
higher_limit

lower_limit = avg - 3*std
lower_limit

df_bookings[df_bookings.revenue_generated<=0]

df_bookings[df_bookings.revenue_generated>higher_limit]

df_bookings = df_bookings[df_bookings.revenue_generated<=higher_limit]
df_bookings.shape

df_bookings.revenue_realized.describe()

higher_limit = df_bookings.revenue_realized.mean() + 3*df_bookings.revenue_realized.std()
higher_limit

df_bookings[df_bookings.revenue_realized>higher_limit]

"""One observation we can have in above dataframe is that all rooms are RT4 which means presidential suit. Now since RT4 is a luxurious room it is likely their rent will be higher. To make a fair analysis, we need to do data analysis only on RT4 room types"""

df_bookings[df_bookings.room_category=="RT4"].revenue_realized.describe()

# mean + 3*standard deviation
23439+3*9048

"""Here higher limit comes to be 50583 and in our dataframe above we can see that max value for revenue realized is 45220. Hence we can conclude that there is no outlier and we don't need to do any data cleaning on this particular column"""

df_bookings[df_bookings.booking_id=="May012216558RT213"]

df_bookings.isnull().sum()

"""Total values in our dataframe is 134576. Out of that 77899 rows has null rating. Since there are many rows with null rating, we should not filter these values. Also we should not replace this rating with a median or mean rating etc

**Exercise-1. In aggregate bookings find columns that have null values. Fill these null values with whatever you think is the appropriate subtitute (possible ways is to use mean or median)**
"""

df_agg_bookings.isnull().sum()

df_agg_bookings[df_agg_bookings.capacity.isna()]

df_agg_bookings.capacity.median()

df_agg_bookings.capacity.fillna(df_agg_bookings.capacity.median(), inplace=True)

df_agg_bookings.loc[[8,15]]

"""**Exercise-2. In aggregate bookings find out records that have successful_bookings value greater than capacity. Filter those records**"""

df_agg_bookings[df_agg_bookings.successful_bookings>df_agg_bookings.capacity]

df_agg_bookings.shape

df_agg_bookings = df_agg_bookings[df_agg_bookings.successful_bookings<=df_agg_bookings.capacity]
df_agg_bookings.shape



"""***
### ==> 3. Data Transformation
***

**Create occupancy percentage column**
"""

df_agg_bookings.head(3)

df_agg_bookings['occ_pct'] = df_agg_bookings.apply(lambda row: row['successful_bookings']/row['capacity'], axis=1)

"""You can use following approach to get rid of SettingWithCopyWarning"""

new_col = df_agg_bookings.apply(lambda row: row['successful_bookings']/row['capacity'], axis=1)
df_agg_bookings = df_agg_bookings.assign(occ_pct=new_col.values)
df_agg_bookings.head(3)

"""Convert it to a percentage value"""

df_agg_bookings['occ_pct'] = df_agg_bookings['occ_pct'].apply(lambda x: round(x*100, 2))
df_agg_bookings.head(3)

df_bookings.head()

df_agg_bookings.info()

"""There are various types of data transformations that you may have to perform based on the need. Few examples of data transformations are,

1. Creating new columns
1. Normalization
1. Merging data
1. Aggregation

***
### ==> 4. Insights Generation
***

**1. What is an average occupancy rate in each of the room categories?**
"""

df_agg_bookings.head(3)

df_agg_bookings.groupby("room_category")["occ_pct"].mean()

"""I don't understand RT1, RT2 etc. Print room categories such as Standard, Premium, Elite etc along with average occupancy percentage"""

df = pd.merge(df_agg_bookings, df_rooms, left_on="room_category", right_on="room_id")
df.head(4)

df.drop("room_id",axis=1, inplace=True)
df.head(4)

df.groupby("room_class")["occ_pct"].mean()

df[df.room_class=="Standard"].occ_pct.mean()

"""**2. Print average occupancy rate per city**"""

df_hotels.head(3)

df = pd.merge(df, df_hotels, on="property_id")
df.head(3)

df.groupby("city")["occ_pct"].mean()

"""**3. When was the occupancy better? Weekday or Weekend?**"""

df_date.head(3)

df = pd.merge(df, df_date, left_on="check_in_date", right_on="date")
df.head(3)

df.groupby("day_type")["occ_pct"].mean().round(2)

"""**4: In the month of June, what is the occupancy for different cities**"""

df_june_22 = df[df["mmm yy"]=="Jun 22"]
df_june_22.head(4)

df_june_22.groupby('city')['occ_pct'].mean().round(2).sort_values(ascending=False)

df_june_22.groupby('city')['occ_pct'].mean().round(2).sort_values(ascending=False).plot(kind="bar")

"""**5: We got new data for the month of august. Append that to existing data**"""

df_august = pd.read_csv("/content/new_data_august.csv")
df_august.head(3)

df_august.columns

df.columns

df_august.shape

df.shape

latest_df = pd.concat([df, df_august], ignore_index = True, axis = 0)
latest_df.tail(10)

latest_df.shape

"""**6. Print revenue realized per city**"""

df_bookings.head()

df_hotels.head(3)

df_bookings_all = pd.merge(df_bookings, df_hotels, on="property_id")
df_bookings_all.head(3)

df_bookings_all.groupby("city")["revenue_realized"].sum()

"""**7. Print month by month revenue**"""

df_date.head(3)

df_date["mmm yy"].unique()

df_bookings_all.head(3)

df_date.info()

df_date["date"] = pd.to_datetime(df_date["date"])
df_date.head(3)

df_bookings_all.info()

df_bookings_all["check_in_date"] = pd.to_datetime(df_bookings_all["check_in_date"], format='mixed')
df_bookings_all.head(3)

df_bookings_all = pd.merge(df_bookings_all, df_date, left_on="check_in_date", right_on="date")
df_bookings_all.head(3)

df_bookings_all.groupby("mmm yy")["revenue_realized"].sum()

"""**Exercise-1. Print revenue realized per hotel type**"""

df_bookings_all.property_name.unique()

df_bookings_all.groupby("property_name")["revenue_realized"].sum().round(2).sort_values()

"""**Exercise-2 Print average rating per city**"""

df_bookings_all.groupby("city")["ratings_given"].mean().round(2)

"""**Exercise-3 Print a pie chart of revenue realized per booking platform**"""

df_bookings_all.groupby("booking_platform")["revenue_realized"].sum().plot(kind="pie")